### ISSUE TITLE
Fix Polling

### ISSUE THREAD

**Issue by tylerkrupicka** [jimmified/jimmify-web#3]
Depends on a server change. The idea is to have the server return the queue position when you submit a query and poll, so that we can base the polling time off of the minimum amount of time it would take to get to your position.

**Comment by jlyneu** [comment]
https://github.com/jimmified/jimmify-web/commit/674fca63c8050dc55b9931be477bb1a797946ede If the question is in the top 20 positions in the queue, then the client will poll the server once every 10 seconds. Otherwise, the client will poll the server after 5 * (position + 1) seconds up to a maximum of 5 minutes.

**Comment by tylerkrupicka** [comment]
i think it would be reasonable to increase the cap to as high as 20 minutes or more since only the first 10 are viewable and it is entirely possible people would have to wait half an hour for a response if they were position 500

**Comment by jlyneu** [comment]
https://github.com/jimmified/jimmify-web/commit/eef98e27b02f650b5dd0e3d3974a13e3979ccd85 done son

**Comment by tylerkrupicka** [comment]
ayy
